### ISSUE TITLE
Don't expand an external table schema after call to resource.infer or validate_resource

### ISSUE THREAD

**Issue by fjuniorr** [frictionlessdata/frictionless-py#904] opened 2021-09-10 19:34 UTC
# Overview

If I have an original data package with an external table schema stored in `schema/estados.json` such as

```json
{
  "profile": "tabular-data-package",
  "resources": [
    {
      "profile": "tabular-data-resource",
      "name": "estados",
      "path": "data/estados.csv",
      "schema": "schema/estados.json" 
    }
  ],
  "name": "datapackage-reprex"
}
```

After a call to `resource.infer` and serialisation to disk with

```python
from frictionless import Package

dp = Package('datapackage.json')
dp.get_resource('estados').infer(stats = True) # a call to validate_resource yields the same outcome
dp.to_json('datapackage.json')
```

The table schema in the new data package is fully expanded

```json
{
  "profile": "tabular-data-package",
  "resources": [
    {
      "profile": "tabular-data-resource",
      "name": "estados",
      "path": "data/estados.csv",
      "schema": {
        "fields": [
          {
            "name": "COD",
            "type": "integer",
            "format": "default",
            "description": "Código de dois dígitos que identificam o estado\n\n> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n",
            "title": "Código do Estado"
          },
          {
            "name": "NOME",
            "type": "string",
            "format": "default",
            "title": "Nome do Estado"
          },
          {
            "name": "SIGLA",
            "type": "string",
            "format": "default",
            "title": "Sigla do Estado"
          }
        ],
        "primaryKey": "COD"
      },
      "scheme": "file",
      "format": "csv",
      "hashing": "md5",
      "stats": {
        "hash": "99167485b6ca41cfa6a97dc8bdf39fa1",
        "bytes": 496,
        "fields": 3,
        "rows": 27
      },
      "encoding": "utf-8"
    }
  ],
  "name": "datapackage-reprex"
}
```

Is this the intended behaviour? In my use case I would like to update the `datapackage.json` with the new stats information, but without expanding the table schema. 

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment] 2021-09-13 11:01
Hi @fjuniorr,

Thanks. I think it's not the intended behavior. I would call it a bug

**Comment by roll** [comment] 2022-07-01 07:08
FIXED in https://github.com/frictionlessdata/frictionless-py/pull/1119 (v5)

**Closed as completed by roll** 2022-07-01 07:08 UTC
Labels: general
