### ISSUE TITLE
pyintaller does not work with frictionless

### ISSUE THREAD

**Issue by Najmatik** [frictionlessdata/frictionless-py#497] opened 2020-10-30 15:21 UTC
Hi,
im trying to implement a simple data check tool that i want to make executable.
If i run it via Python its working as expected. If i try to make it executable via pyinstaller there are some issues. Here is the log:

```
(frictionless) ubuntu@ubuntu-F6:~$ pyinstaller dq_check
121 INFO: PyInstaller: 4.0
121 INFO: Python: 3.8.5
148 INFO: Platform: Linux-5.4.0-52-generic-x86_64-with-glibc2.29
149 INFO: wrote /home/ubuntu/dq_check.spec
154 INFO: UPX is not available.
script '/home/ubuntu/dq_check' not found
(frictionless) ubuntu@ubuntu-F6:~$ pyinstaller /home/ubuntu/Schreibtisch/code/dq-check.py
92 INFO: PyInstaller: 4.0
92 INFO: Python: 3.8.5
115 INFO: Platform: Linux-5.4.0-52-generic-x86_64-with-glibc2.29
116 INFO: wrote /home/ubuntu/dq-check.spec
120 INFO: UPX is not available.
122 INFO: Extending PYTHONPATH with paths
['/home/ubuntu/Schreibtisch/code', '/home/ubuntu']
153 INFO: checking Analysis
153 INFO: Building Analysis because Analysis-00.toc is non existent
153 INFO: Initializing module dependency graph...
157 INFO: Caching module graph hooks...
177 INFO: Analyzing base_library.zip ...
5450 INFO: Processing pre-find module path hook distutils from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
5452 INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.8'
13284 INFO: Caching module dependency graph...
13561 INFO: running Analysis Analysis-00.toc
13639 INFO: Analyzing /home/ubuntu/Schreibtisch/code/dq-check.py
14608 INFO: Processing pre-safe import module hook six.moves from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-six.moves.py'.
25364 INFO: Processing pre-safe import module hook setuptools.extern.six.moves from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-setuptools.extern.six.moves.py'.
26305 INFO: Processing pre-find module path hook site from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_find_module_path/hook-site.py'.
26307 INFO: site: retargeting to fake-dir '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/fake-modules'
64613 INFO: Processing module hooks...
64613 INFO: Loading module hook 'hook-openpyxl.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
64705 INFO: Loading module hook 'hook-pycparser.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
64707 INFO: Loading module hook 'hook-cryptography.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
65073 INFO: Loading module hook 'hook-jsonschema.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
65094 INFO: Loading module hook 'hook-botocore.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
65971 INFO: Loading module hook 'hook-certifi.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
65975 INFO: Loading module hook 'hook-sqlite3.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
66080 INFO: Loading module hook 'hook-numpy.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
66082 INFO: Loading module hook 'hook-matplotlib.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
66609 INFO: Loading module hook 'hook-numpy.core.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
66812 INFO: Loading module hook 'hook-PIL.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
66820 INFO: Excluding import 'tkinter'
66834 INFO: Excluding import 'PyQt4'
66850 INFO: Import to be excluded not found: 'PySide'
66851 INFO: Import to be excluded not found: 'FixTk'
66851 INFO: Excluding import 'PyQt5'
66857 INFO:   Removing import of PyQt5 from module PIL.ImageQt
66858 INFO: Loading module hook 'hook-importlib_metadata.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
66862 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
66863 INFO: Loading module hook 'hook-lib2to3.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
66899 INFO: Loading module hook 'hook-distutils.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
66903 INFO: Loading module hook 'hook-pytz.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
66908 INFO: Loading module hook 'hook-setuptools.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
68200 INFO: Loading module hook 'hook-pandas.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
69493 INFO: Loading module hook 'hook-xml.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
69782 INFO: Loading module hook 'hook-sqlalchemy.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
70174 INFO:   Found 4 sqlalchemy hidden imports
70175 WARNING: Hidden import "pysqlite2" not found!
70176 WARNING: Hidden import "MySQLdb" not found!
70176 WARNING: Hidden import "psycopg2" not found!
72312 WARNING: Hidden import "sqlalchemy.sql.functions.func" not found!
72317 INFO: Import to be excluded not found: 'sqlalchemy.testing'
72318 INFO: Loading module hook 'hook-pkg_resources.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
73403 INFO: Processing pre-safe import module hook win32com from '/home/ubuntu/.local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
73533 WARNING: Hidden import "pkg_resources.markers" not found!
73538 INFO: Excluding import '__main__'
73544 INFO:   Removing import of __main__ from module pkg_resources
73545 INFO: Loading module hook 'hook-encodings.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
73667 INFO: Loading module hook 'hook-PIL.Image.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
74604 INFO: Loading module hook 'hook-matplotlib.backends.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
76370 INFO:   Matplotlib backend "GTK3Agg": added
77503 INFO:   Matplotlib backend "GTK3Cairo": added
78001 INFO:   Matplotlib backend "MacOSX": ignored
    cannot import name '_macosx' from 'matplotlib.backends' (/home/ubuntu/.local/lib/python3.8/site-packages/matplotlib/backends/__init__.py)
78503 INFO:   Matplotlib backend "nbAgg": ignored
    No module named 'IPython'
79170 INFO:   Matplotlib backend "Qt4Agg": ignored
    Failed to import any qt binding
79836 INFO:   Matplotlib backend "Qt4Cairo": ignored
    Failed to import any qt binding
80501 INFO:   Matplotlib backend "Qt5Agg": ignored
    Failed to import any qt binding
81163 INFO:   Matplotlib backend "Qt5Cairo": ignored
    Failed to import any qt binding
82114 INFO:   Matplotlib backend "TkAgg": added
83010 INFO:   Matplotlib backend "TkCairo": added
83521 INFO:   Matplotlib backend "WebAgg": ignored
    Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/matplotlib/backends/backend_webagg.py", line 27, in <module>
    import tornado
ModuleNotFoundError: No module named 'tornado'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/matplotlib/backends/backend_webagg.py", line 29, in <module>
    raise RuntimeError("The WebAgg backend requires Tornado.") from err
RuntimeError: The WebAgg backend requires Tornado.
84394 INFO:   Matplotlib backend "WX": ignored
    No module named 'wx'
84899 INFO:   Matplotlib backend "WXAgg": ignored
    No module named 'wx'
85392 INFO:   Matplotlib backend "WXCairo": ignored
    No module named 'wx'
86019 INFO:   Matplotlib backend "agg": added
86647 INFO:   Matplotlib backend "cairo": added
87516 INFO:   Matplotlib backend "pdf": added
88397 INFO:   Matplotlib backend "pgf": added
89030 INFO:   Matplotlib backend "ps": added
89678 INFO:   Matplotlib backend "svg": added
90552 INFO:   Matplotlib backend "template": added
91066 INFO: Processing pre-safe import module hook gi.repository.Gio from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.Gio.py'.
91068 INFO: Processing pre-safe import module hook gi.repository.GLib from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.GLib.py'.
91070 INFO: Processing pre-safe import module hook gi.repository.GObject from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.GObject.py'.
91071 INFO: Processing pre-safe import module hook gi.repository.Gtk from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.Gtk.py'.
91072 INFO: Processing pre-safe import module hook gi.repository.Gdk from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.Gdk.py'.
91814 INFO: Loading module hook 'hook-gi.repository.Gtk.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
112615 INFO: Processing pre-safe import module hook gi.repository.xlib from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.xlib.py'.
112617 INFO: Processing pre-safe import module hook gi.repository.Atk from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.Atk.py'.
112626 INFO: Loading module hook 'hook-sysconfig.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
112652 INFO: Loading module hook 'hook-gi.repository.Atk.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
113008 INFO: Loading module hook 'hook-_tkinter.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
113249 INFO: checking Tree
113250 INFO: Building Tree because Tree-00.toc is non existent
113250 INFO: Building Tree Tree-00.toc
113267 INFO: checking Tree
113267 INFO: Building Tree because Tree-01.toc is non existent
113267 INFO: Building Tree Tree-01.toc
113361 INFO: Loading module hook 'hook-gi.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
113390 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
113400 INFO: Import to be excluded not found: 'FixTk'
113400 INFO: Excluding import 'tkinter'
113405 INFO: Loading module hook 'hook-gi.repository.GLib.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
114001 INFO: Loading module hook 'hook-gi.repository.Gdk.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
114328 INFO: Processing pre-safe import module hook gi.repository.cairo from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.cairo.py'.
114331 INFO: Processing pre-safe import module hook gi.repository.Pango from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.Pango.py'.
114333 INFO: Processing pre-safe import module hook gi.repository.GdkPixbuf from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.GdkPixbuf.py'.
114335 INFO: Loading module hook 'hook-gi.repository.Gio.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
114856 INFO: Loading module hook 'hook-gi.repository.xlib.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
115127 INFO: Loading module hook 'hook-gi.repository.GObject.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
115466 WARNING: Hidden import "gi._gobject" not found!
115467 INFO: Loading module hook 'hook-gi.repository.cairo.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
115767 INFO: Loading module hook 'hook-gi.repository.Pango.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
116068 INFO: Loading module hook 'hook-gi.repository.GdkPixbuf.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
116694 INFO: Processing pre-safe import module hook gi.repository.GModule from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.GModule.py'.
116696 INFO: Loading module hook 'hook-gi.repository.GModule.py' from '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
117553 INFO: Looking for ctypes DLLs
117910 WARNING: library user32 required via ctypes not found
118018 WARNING: library msvcrt required via ctypes not found
118041 INFO: Analyzing run-time hooks ...
118088 INFO: Including run-time hook '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth__tkinter.py'
118092 INFO: Including run-time hook '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
118099 INFO: Including run-time hook '/home/ubuntu/.local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/rthooks/pyi_rth_certifi.py'
118101 INFO: Including run-time hook '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgres.py'
118104 INFO: Including run-time hook '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_gdkpixbuf.py'
118108 INFO: Including run-time hook '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_gtk.py'
118111 INFO: Including run-time hook '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_glib.py'
118113 INFO: Including run-time hook '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_gio.py'
118115 INFO: Including run-time hook '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_gi.py'
118117 INFO: Including run-time hook '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_mplconfig.py'
118121 INFO: Including run-time hook '/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_mpldata.py'
118203 INFO: Looking for dynamic libraries
126789 INFO: Looking for eggs
126789 INFO: Python library not in binary dependencies. Doing additional searching...
126874 INFO: Using Python library /lib/x86_64-linux-gnu/libpython3.8.so.1.0
126930 INFO: Warnings written to /home/ubuntu/build/dq-check/warn-dq-check.txt
127363 INFO: Graph cross-reference written to /home/ubuntu/build/dq-check/xref-dq-check.html
130752 INFO: checking PYZ
130752 INFO: Building PYZ because PYZ-00.toc is non existent
130752 INFO: Building PYZ (ZlibArchive) /home/ubuntu/build/dq-check/PYZ-00.pyz
135365 INFO: Building PYZ (ZlibArchive) /home/ubuntu/build/dq-check/PYZ-00.pyz completed successfully.
135466 INFO: checking PKG
135466 INFO: Building PKG because PKG-00.toc is non existent
135466 INFO: Building PKG (CArchive) PKG-00.pkg
135590 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
135593 INFO: Bootloader /home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/bootloader/Linux-64bit/run
135593 INFO: checking EXE
135593 INFO: Building EXE because EXE-00.toc is non existent
135593 INFO: Building EXE from EXE-00.toc
135597 INFO: Appending archive to ELF section in EXE /home/ubuntu/build/dq-check/dq-check
135710 INFO: Building EXE from EXE-00.toc completed successfully.
135884 INFO: checking COLLECT
135884 INFO: Building COLLECT because COLLECT-00.toc is non existent
135884 INFO: Building COLLECT COLLECT-00.toc
203961 INFO: Building COLLECT COLLECT-00.toc completed successfully.
```

Pyinstaller does not even try to catch frictionless. Same happens with cx-freeze.

What did i do:

I created a virtualenv and installed frictionless and pyinstaller(cx-freeze) with pip.
I used the latest versions with Python 3.8.5.
Then i ran "pyinstaller dq_check".
If i try to run the resulting executable there are some import errors:

```
Traceback (most recent call last):
  File "dq-check.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "frictionless/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "frictionless/check.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "frictionless/metadata.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "frictionless/helpers.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/ubuntu/.local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "frictionless/config.py", line 19, in <module>
  File "frictionless/config.py", line 13, in read_asset
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/dist/dq-check/frictionless/assets/VERSION'
[42657] Failed to execute script dq-check
```
Thanks in advance for any help and suggestions!

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment] 2020-11-02 08:19
Hi @Najmatik,

I'm not familiar with `pyinstaller` but it seems the problem is that `pyinstaller` ignores `frictionless` static files in the `frictionless/assets` folder. You need to find some way to add it to the bundle - https://stackoverflow.com/questions/59966120/how-to-add-statichtml-css-js-files-in-pyinstaller-to-create-standalone-exe-f

I'm closing as it's not Frictionless-related and I would recommend asking for help here also - https://discord.com/channels/695635777199145130/695635777199145133 - maybe someone has worked with `pyinstaller`. As an option maybe there is a `pyinstaller` chat to get help. Actually, it must be a very common problem as you just use `frictionless` as an external dependency.

**Closed as completed by roll** 2020-11-02 08:19 UTC
Labels: question
