### ISSUE TITLE
Reporting unexpected delimiter

### ISSUE THREAD

**Issue by cbenz** [frictionlessdata/frictionless-py#285] opened 2018-10-01 16:24 UTC
Hi, this issue is mainly to discuss about a use case I have.

I'd like to validate a CSV file using the `,` delimiter. I would expect to see in the report an error with code `invalid-delimiter`.

For now, if I specify the delimiter to `goodtables.Inspector.inspect`, it is passed to `tabulator.parsers.csv` but no error is raised: if the delimiter isn't detected, either several classic delimiters are tried (one of `,\t;|`, cf [`tabulator.parsers.csv`](https://github.com/frictionlessdata/tabulator-py/blob/6de4487ad590992dab068d71cfec582a980bd362/tabulator/parsers/csv.py#L117)), otherwise a one-column table is parsed (like `["A;B;C"]` instead of `["A", "B", "C"]`).

How should this be implemented? Should `tabulator.parsers.csv` be improved to return a `SourceError` with a message of the type "Could not determine delimiter: expected ',' but detected ';'"? A sub-problem is that this SourceError is not specific enough to carry the expected delimiter and the detected one. 

Should specific errors be created in tabulator, like `class InvalidDelimiter(SourceError)`, with `detected_delimiter` and `expected_delimiter` fields? Or introduce a generic `tabulator.Error` with a `code` attribute, like the one used in `goodtables.Error` and `spec.json`, and introduce a new `code=invalid-delimiter`?
This would allow Goodtables to catch these errors and return "message data" in the spirit of what have been done in #280 

I tried this in my fork: https://github.com/Jailbreak-Paris/tabulator-py/commit/bced32509cb5993d6c09626492d844b007847bb3
 
This adds to the report an error of code `source-error`:

```python
{'error-count': 1,
 'preset': 'table',
 'table-count': 1,
 'tables': [{'error-count': 1,
             'errors': [{'code': 'source-error',
                         'message': 'Could not determine delimiter: expected '
                                    "',' but detected ';'",
                         'message-data': {}}],
             'format': 'csv',
             'headers': [],
             'row-count': 0,
             'schema': 'table-schema',
             'scheme': 'text',
             'source': 'A;B;C\na;b;c',
             'time': 0.004,
             'valid': False}],
 'time': 0.006,
 'valid': False,
 'warnings': []}
```

I'm very curious to know what you think about it!

**Comment by roll** [comment] 2019-08-19 07:22
Sorry I missed this one. 

The problem as often it happens to `goodtables` that Data Quality Spec doesn't provide such an error - https://github.com/frictionlessdata/data-quality-spec

Stale Bot, please don't close this on it's upgraded to be a feature request.

**Comment by roll** [comment] 2020-09-26 09:05
I'm closing this issue as it seems to be out of the current framework's scope. By design, delimiter detections happen only if there is no explicitly provided delimiter so it doesn't compare detected with provided.

Starting from `frictionless` aka `goodtables@3` - https://github.com/frictionlessdata/frictionless-py#frictionless-for-python - a detected delimiter is a part of validation report `tables[].dialect.delimiter` so a client can write a high-level check to ensure that delimiter is correct.

I'm closing it for now although it's something we might bring back to the discussion later.

**Closed by roll** 2020-09-26 09:05 UTC
Labels: feature
